### ISSUE TITLE
new plugin-tools creates source map files with plugin-id included in webpack path

### ISSUE THREAD

**Issue by briangann** [grafana/plugin-validator#140]
when using yarn v3/v4 (and any other package manager), the source map file ends up with paths like this:

```
webpack://briangann-gauge-panel/webpack/bootstrap
webpack://briangann-gauge-panel/./components/TickMaps/TickMapItem.tsx
```

the sourcediff code is only removing the leading `webpack://` which results in the tool reporting the source does not match

this was encountered using the standard plugin-tools environment but with yarn v3 in this repo https://github.com/briangann/grafana-gauge-panel/releases/tag/v2.0.0

**Comment by briangann** [comment]
this doesn't appear to be limited to yarn v3, the current create-plugin setup is generating the source maps with the same paths as above

**Comment by jackw** [comment]
As you've already discovered @briangann this isn't to do with package managers. Based on the logs I'm inclined to think it's due to the changes in the webpack config which enable [lazy loading](https://github.com/grafana/plugin-tools/pull/427) and prevent the additional [webpack runtimes from conflicting](https://github.com/grafana/plugin-tools/pull/464).
